php_version: 7.1
global_exclude_dirs:
    - vendor
    - system
    - modules/auth
    - modules/cache
    - modules/database
    - modules/device
    - modules/email
    - modules/i18n-plural
    - modules/image
    - modules/minion
    - modules/migrations
    - modules/mysqli
    - modules/orm
    - modules/paginate
    - modules/static-files
    - modules/sqlite
    - modules/ulogin
    - modules/unittests
    - modules/utils
    - modules/admin/static-files/admin/components

exclude_patterns:
- modules/*/node_modules/*
- modules/*/static-files/*/node_modules/*

rules:
    php.use_global_variable_or_function:
        enabled: true
    web.non_utf8_encoding:
        enabled: true
    php.use_php_eval_function:
        enabled: true
    php.use_exit_function:
        enabled: true
    doctrine.database_query_contains_string_and_variable_concatenation:
        enabled: true
    php.missing_use_statement:
        enabled: false
    php.use_php_sleep_function:
        enabled: false
    php.silenced_error:
        enabled: false
    php.dynamically_change_configuration:
        enabled: false
    task_todo_comment:
        enabled: false
    php.neglected_tests:
        enabled: false
