#!/bin/bash

# Get current working directory (it was set in site-related cron script)
SITE_DIR=$(pwd)

# Get current script directory (it is BetaKiller core root)
CORE_DIR=$(dirname $(readlink -f $0))

SITE_TASKS_DIR="$SITE_DIR/tasks"
CORE_TASKS_DIR="$CORE_DIR/tasks"

#echo $SITE_TASKS_DIR
#echo $CORE_TASKS_DIR

CRUNZ="$CORE_DIR/vendor/bin/crunz"

# Run site-related cron tasks first
echo "Executing site-related tasks..."
${CRUNZ} schedule:run ${SITE_TASKS_DIR} -vvv
echo "Done!"

# Run core tasks last
echo "Executing core tasks..."
${CRUNZ} schedule:run ${CORE_TASKS_DIR} -vvv
echo "Done!"
