<?php defined('SYSPATH') OR die('No direct script access.');

class Ulogin extends Kohana_Ulogin {

    // TODO call to API
//    protected function create_new_user(array $user_data)
//    {
//        return parent::create_new_user($user_data); // TODO: Change the autogenerated stub
//    }

}