<?php
namespace BetaKiller\Repository;

use BetaKiller\Content\ContentElementRepositoryInterface;
use BetaKiller\Content\RepositoryHasWordpressIdAndPathInterface;

interface WordpressAttachmentRepositoryInterface extends ContentElementRepositoryInterface, RepositoryHasWordpressIdAndPathInterface {}
