<?php defined('SYSPATH') OR die('No direct script access.');

class Controller_Admin extends Controller_Basic {

    public function before()
    {
        // Hide from unauthorized users
        if ( ! Env::user(TRUE) )
            throw new HTTP_Exception_404();

        parent::before(); // TODO: Change the autogenerated stub
    }

}