<?php defined('SYSPATH') OR die('No direct script access.');

class IFace_Auth_Login extends IFace {

    /**
     * @var string Default url for relocate after successful login
     */
    protected $_redirect_url = "/";



    public function get_data()
    {
        // TODO: Change the autogenerated stub
    }

    public function redirect_to_current_page()
    {
        $this->_redirect_url = Request::current()->uri();
    }

}