<?php defined('SYSPATH') OR die('No direct script access.');

/**
 * Class View_Template
 *
 * Template wrapper with set_title() / get_title() helpers
 */
class View_Template extends View_Wrapper {

    public $_wrapper = 'html';

    protected static function get_view_path()
    {
        return 'templates';
    }

    public function render($file = NULL)
    {
        $wrapper = View_Wrapper::factory($this->_wrapper);
        return parent::render($file); // TODO: Change the autogenerated stub
    }


}
